### PR TITLE
__setitem__ key type check

### PR DESCRIPTION
**Pull request by JakubBlaha**
Doing something like
```python
JsonStore('test.json')[1] = 2
```
resulted in the error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jsonstore.py", line 154, in __setitem__
    path, _, key = name.rpartition(".")
AttributeError: 'int' object has no attribute 'rpartition'
```
which didn't really tell what the problem is. Therefore I have added a check for the `name` parameter in the `__setitem__` method, which will now raise a `TypeError` if something other then a `str` is used as a key.

### CODE REVIEW

**Comment by JakubBlaha** [comment]
Also sorry about all of the commits. I am quite new to working with git and don't really know how to clean it up...

**Comment by Code0x58** [comment]
Thanks for reporting and working on this @JakubBlaha! I think the PR would disallow things like `store["list", 1:]`, so I had a go at it in last night in #6 and tried to clean up some of the code and exceptions. Would you mind reviewing it to see if it helps in the case you encountered?

Re. using git, you can do things like `git commit --amend` to overwrite your last commit to include your new changes, or with you get to the end of a chain of commits, you might find something like `git rebase -i` helpful. The docs [here](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) look like they're good on the topic.

**Comment by JakubBlaha** [comment]
Thanks a lot for rewriting so much of the code! Now I am even more exceited to use this amazing library.

The only thing that this library is missing now is a support to directly append to lists stored in a json file. I would be really excited to work on this feture. I am unsure about few things and probably would need a bit of advice. Should I open a new issue?

**Comment by Code0x58** [comment]
:D That PR may now allow you to do the direct appending in a sneaky way with slices:
```python
store.list = ["foo"]
# as long as the slice start is >= the list length this will work
store["list", 9999:] = ["bar"]
assert store.list == ["foo", "bar"]
```
... I just had a play, and it looks like you just do:
```python
store.list = ["foo"]
# as long as the slice start is >= the list length this will work
store["list"] += ["bar"]
assert store.list == ["foo", "bar"]
```
Adding to the README and a test to make sure all behaves as expected sounds good to me, maybe something like this:
```python
store.list = []
extension = [{"key": "value"}]

# make sure += happens
store["list"] += extension
store.list += extension
assert len(store.list) == 2

# make sure a deepcopy occurred
assert store.list[0] is not extension[0]
```

**Comment by JakubBlaha** [comment]
This is interesting. I thought this would not work since you are using deepcopying.
https://github.com/Code0x58/python-jsonstore/blob/542a3c3bd185cf156b96be60b6c4763f98ee4c52/jsonstore.py#L166

Edit: I am talking about this: `store["list"] += extension`

**Comment by Code0x58** [comment]
Given this magic method behaviour [[src](https://docs.python.org/3/reference/datamodel.html#object.__iadd__)]:
> If a specific method is not defined, the augmented assignment falls back to the normal methods. For instance, if x is an instance of a class with an \_\_iadd\_\_() method, x += y is equivalent to x = x.\_\_iadd\_\_(y) . Otherwise, x.\_\_add\_\_(y) and y.\_\_radd\_\_(x) are considered, as with the evaluation of x + y.

I think `store["list"] += extension` gets evaluated as `store["list"] = store["list"] + extension`, which my do more copies than absolutely needed, but should get the job done.

As long as you use things like `store[key1, key2, ...] += extension` the deepcopying shouldn't get in your way. It would stop things like `store.dict["list"] += extension` or `store.list.extend(extension)` from behaving as you might hope though.

Tests may be best for making sure though

**Pull request closed without merging**
